config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"

  namespace :api do
    resources :users, only: [] do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :create, :new, :destroy] do
      resources :comments, only: [:create, :new, :destroy]
      resources :likes, only: [:create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :read, :all

    if user.role == 'admin'
      can :manage, :all
    else
      can :manage, Post, author: user
      can :manage, Comment, author: user
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'
  after_save :comments_count

  def comments_count
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'
  after_save :likes_count

  def likes_count
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :likes, foreign_key: 'post_id'
  has_many :comments, foreign_key: 'post_id'
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }
  after_save :post_counter

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def post_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable, :lockable
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  validates :name, presence: true, length: { maximum: 50 }
  validates :posts_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ActionController::API
  respond_to :json
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < Api::ApplicationController
  def index
    @comments = Comment.all.where(author_id: params[:user_id], post_id: params[:post_id])
    render json: @comments
  end

  def create
    request_body = JSON.parse(request.body.read)
    comment = Comment.new(author_id: current_user.id, post_id: params.require(:post_id), text: request_body['comment'])
    render json: comment
  end

  private

  def comment_body
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < Api::ApplicationController
  def index
    @posts = Post.all.where(author_id: params.require(:user_id))
    render json: @posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit({ roles: [] }, :name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    post = Post.find_by(id: params[:post_id])
    @comment = Comment.new(post:, author: current_user, text: comment_params[:text])
    redirect_to user_posts_path if @comment.save
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:success] = 'Post was deleted successfully'
    redirect_to user_post_path(params[:user_id], params[:post_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new(author: current_user, post: Post.find_by(id: params[:post_id]))
    redirect_to user_posts_path(user_id: params[:user_id], id: params[:id]) if @like.save
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @posts = Post.where(author_id: params[:user_id])
    @users_find = User.includes(:posts).find(params[:user_id])
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find_by(id: params[:id])
    return unless @post.nil?

    flash[:error] = 'Post not found'
    redirect_to action: :index
    @comment = Comment.new
    @like = Like.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.likes_counter = 0
    @post.comments_counter = 0

    return unless @post.save

    redirect_to user_posts_path(user_id: params[:user_id])
    flash[:success] = 'Saved Successfully'
  end

  def destroy
    @post.comments.destroy_all
    @post.likes.destroy_all
    @post.destroy
    flash[:success] = 'Post was deleted successfully'
    redirect_to user_posts_path(current_user.id)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users_all = User.all
    @user = current_user
  end

  def show
    if params[:id] == 'Sign out'
      redirect_to root_path
    else
      @users_find = User.find(params[:id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1>Comments for post</h1>
<%= form_with model: @comment, url:user_post_comments_path(post_id: params[:post_id]) do |form| %>
    <%= form.text_area :text, placeholder: "Add Comment"%>
    <br/>
    <%= form.submit "Comment"%>
    </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %>
    <p>Signed in as:<%= current_user.name %></p>
    <a href="/">Home</a>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <a href="/users/sign_in">Sign in</a>
    <% end %>
      <%= yield %>
  </body>
</html>

app/views/partials/_post_container.html.erb
<article>
    <p><%= post.text %></p>
    <div class="block">
        <p>Comments: <%= post.comments_counter %></p>
        <p>Likes: <%= post.likes_counter %></p>
    </div>
    <%= form_with model: @like, url:user_post_likes_path(user_id: post.author.id, post_id: post.id)  do |form|%>
      <%= form.submit "Like" %>
      <br/>
    <% end %>
    <% if can? :destroy, post %>
          <%= link_to "Delete", user_post_path(@users_find.id, post.id), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    } %>
        <% end %>
    <button id="add_comment"><%= link_to 'Add comment', new_user_post_comment_path(user_id: post.author.id, post_id: post.id) %></button>
</article>

app/views/partials/_user_container.html.erb
<div class="user-container">
        <img src=<%= user.photo %> alt="dummy photo">
        <div class="container">
            <div class="username">
                <h2><%= user.name %></h2>
            </div>
            <div class="posts">
                <h3>Number of posts: <%= user.posts_counter %></h3>
            </div>
        </div>
</div>

app/views/posts/index.html.erb
<body>
    <%= render "partials/user_container", user: @users_find %>
    <% @posts.each do |post| %>
        <%= link_to "/users/#{@users_find.id}/posts/#{post.id}" do %>
        <article>
        <h3>Post Title: <%= post.title %></h3>
        </article>
        <% end %>
        <%= render "partials/post_container", post: post %>
        <% post.recent_comments.each do |comment| %>
            <article class="comments-box">
            <%user = User.find_by(id: comment.author_id).name %>
            <p><strong><%=user%>: <%= comment.text %></strong></p>
        </article>
        <% end %>
        <% end %>
        <% (1..3).each do |page| %>
            <%= link_to page, user_posts_path(posts: page) %>
          <% end %>
</body>

app/views/posts/new.html.erb
<h1>Allow users to create comments, posts and a likes counter</h1>

<%= form_with model: @post, url:user_posts_path do |form| %>
    <div>
        <%= form.label :title %><br>
        <%= form.text_field :title, placeholder: 'Title' %>
    </div>
    <div>
        <%= form.label :text %><br>
        <%= form.text_area :text, placeholder: 'Description of post' %>   
    </div>
    <%= form.submit %>
<% end %>

app/views/posts/show.html.erb
<body>
    <article>
    <div class="block-post">
        <div class="post-heading">
            <h3><%= @post.title %> by <%= @user.name %></h3>
        </div>
        <div class="post-comments">
            <p>Comments: <%= @post.comments_counter %></p>
            <p>Likes: <%= @post.likes_counter %></p>
        </div>
    </div>
        <p><%= @post.text %></p>
    </article>

    <% if !@post.comments.empty? %>
    <article class="comments-box">
    <% @post.comments.each do |comment| %>
        <% user = User.find_by(id: comment.author_id).name %>
        <p><strong><%= user %>: <%= comment.text %></strong></p>
        <% if can? :destroy, comment %>
          <%= link_to "Delete", user_post_comment_path(@user.id, @post.id, comment.id), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    } %>
        <% end %>
        <% end %>
    </article>
    <% end %>
</body>

app/views/users/index.html.erb
<body>
    <div class = "create-post">
    <%= link_to new_user_post_path(@user) do %>
    <br/>
    <button>create post</button>
    <% end %>
    </div>  
    <% @users_all.each do |user| %>
        <%= link_to "/users/#{user.id}" do %>
        <%= render "partials/user_container", user: user %>
        <% end %>
    <% end %>
</body>

app/views/users/show.html.erb
<body>
  <%= render "partials/user_container", user: @users_find %>
        <article>
            <h3>Bio</h3>
            <p><%= @users_find.bio %></p>
        </article>

        <% @users_find.recent_posts.each do |post| %>
            <article>
            <h3>Post Title: <%= post.title %></h3>
            <p><%= post.text %></p>
            <div class="block">
                <p>Comments: <%= post.comments_counter %></p>
                <p>Likes: <%= post.likes_counter %></p>
            </div>
        </article>
        <% end %>
        <%= link_to "/users/#{@users_find.id}/posts" do %>
    <button>See all posts</button>
    <% end %>
</body>